[Icon Theme]
Name=multimc
Comment=MultiMC Default Icons
Inherits=default
Directories=scalable/apps,8x8,16x16,22x22,24x24,32x32,48x48,scalable

[scalable/apps]
Size=48
Type=scalable
MinSize=1
MaxSize=512
Context=Applications

[8x8]
Size=8

[16x16]
Size=16

[22x22]
Size=22

[24x24]
Size=24

[32x32]
Size=32

[48x48]
Size=48

[64x64]
Size=64

[256x256]
Size=256

[150x150]
Size=150

[scalable]
Size=48
Type=Scalable
MinSize=16
MaxSize=256
