#include "MSA.h"

#include "minecraft/auth/steps/MSAStep.h"
#include "minecraft/auth/steps/XboxUserStep.h"
#include "minecraft/auth/steps/XboxAuthorizationStep.h"
#include "minecraft/auth/steps/LauncherLoginStep.h"
#include "minecraft/auth/steps/XboxProfileStep.h"
#include "minecraft/auth/steps/EntitlementsStep.h"
#include "minecraft/auth/steps/MinecraftProfileStep.h"
#include "minecraft/auth/steps/GetSkinStep.h"

MSASilent::MSASilent(AccountData* data, QObject* parent) : AuthFlow(data, parent) {
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new MSAStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data, MSAStep::Action::Refresh));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new XboxUserStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new XboxAuthorizationStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data, &hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data->xboxApiToken, "http://xboxlive.com", "Xbox"));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new XboxAuthorizationStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data, &hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data->mojangservicesToken, "rp://api.minecraftservices.com/", "Mojang"));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new LauncherLoginStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new XboxProfileStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new EntitlementsStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new MinecraftProfileStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new GetSkinStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
}

MSAInteractive::MSAInteractive(
    AccountData* data,
    QObject* parent
) : AuthFlow(data, parent) {
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new MSAStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data, MSAStep::Action::Login));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new XboxUserStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new XboxAuthorizationStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data, &hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data->xboxApiToken, "http://xboxlive.com", "Xbox"));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new XboxAuthorizationStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data, &hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data->mojangservicesToken, "rp://api.minecraftservices.com/", "Mojang"));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new LauncherLoginStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new XboxProfileStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new EntitlementsStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new MinecraftProfileStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
    hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_steps.append(new GetSkinStep(hello_developer_i_am_here_to_kindly_tell_you_that_the_following_variable_is_actually_a_member_data));
}
