#!/bin/sh
# Basic start script for running MultiMC with the libs packaged with it.

MMC_DIR="$( cd "$( dirname "$0" )" && pwd )"
cd "${MMC_DIR}"
echo "MultiMC Dir: ${MMC_DIR}"

export LD_LIBRARY_PATH="${MMC_DIR}/bin":$LD_LIBRARY_PATH
export QT_PLUGIN_PATH="${MMC_DIR}/plugins"
export QT_FONTPATH="${MMC_DIR}/fonts"
exec ${MMC_DIR}/bin/MultiMC -d ${MMC_DIR} $@

