#!/bin/bash
# Basic start script for running MultiMC with the libs packaged with it.

MMC_DIR=`dirname "$0"`
cd "${MMC_DIR}"
echo "MultiMC Dir: ${MMC_DIR}"

# Set up env
export LD_LIBRARY_PATH="${MMC_DIR}/bin":$LD_LIBRARY_PATH
export QT_PLUGIN_PATH="${MMC_DIR}/plugins"
export QT_FONTPATH="${MMC_DIR}/fonts"

# Just to be sure...
chmod +x "${MMC_DIR}/bin/MultiMC"

# run MultiMC
"${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" $@

