// OFFLINE MODE LAUNCH POINT
// Modify existing GenerateProfile or create wrapper
//
// Key changes needed for offline mode:
// 1. Check if account is offline type
// 2. Skip all Mojang/Microsoft API calls
// 3. Use locally generated UUID
// 4. Generate valid session string
// 5. Allow direct game launch

#include "GenerateProfile.h"
#include "minecraft/auth/MinecraftAccount.h"
#include "minecraft/auth/AccountData.h"
#include "launch/LaunchTask.h"

#include <QDebug>

void GenerateProfile::executeTask()
{
    auto account = m_parent->auth();
    if (!account) {
        emitFailed(tr("No account selected"));
        return;
    }

    // Check if this is an offline account
    if (account->accountType() == AccountType::Offline) {
        emit logLine(tr("Generating offline profile for: %1").arg(account->profileName()), MessageLevel::Launcher);
        
        // For offline accounts, skip all server calls
        // Profile is already generated by MinecraftAccount::createOffline()
        auto session = std::make_shared<AuthSession>();
        account->fillSession(session);
        
        emit logLine(tr("Player: %1").arg(session->player_name), MessageLevel::Launcher);
        emit logLine(tr("UUID: %1").arg(session->uuid), MessageLevel::Launcher);
        emit logLine(tr("Session Type: Offline"), MessageLevel::Launcher);
        
        m_parent->setSession(session);
        emitSucceeded();
        return;
    }

    // For online accounts, proceed with normal flow
    // (existing code)
}
