
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Users/Sameer/.gemini/antigravity/bin/"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/"
      - "C:/Python314/Scripts/"
      - "C:/Python314/"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/Microsoft VS Code/bin/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/nodejs/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files/PuTTY/"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "C:/Users/Sameer/AppData/Roaming/npm/"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/"
    searched_directories:
      - "C:/Users/Sameer/.gemini/antigravity/bin/ninja-build.com"
      - "C:/Users/Sameer/.gemini/antigravity/bin/ninja-build.exe"
      - "C:/Users/Sameer/.gemini/antigravity/bin/ninja-build"
      - "C:/Users/Sameer/.gemini/antigravity/bin/ninja.com"
      - "C:/Users/Sameer/.gemini/antigravity/bin/ninja.exe"
      - "C:/Users/Sameer/.gemini/antigravity/bin/ninja"
      - "C:/Users/Sameer/.gemini/antigravity/bin/samu.com"
      - "C:/Users/Sameer/.gemini/antigravity/bin/samu.exe"
      - "C:/Users/Sameer/.gemini/antigravity/bin/samu"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/ninja-build.com"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/ninja-build.exe"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/ninja-build"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/ninja.com"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/ninja.exe"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/ninja"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/samu.com"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/samu.exe"
      - "C:/Users/Sameer/AppData/Roaming/Antigravity/bin/samu"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/ninja-build.com"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/ninja-build.exe"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/ninja-build"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/ninja.com"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/ninja.exe"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/ninja"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/samu.com"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/samu.exe"
      - "C:/Program Files/AdoptOpenJDK/jre-11.0.8.10-hotspot/bin/samu"
      - "C:/Python314/Scripts/ninja-build.com"
      - "C:/Python314/Scripts/ninja-build.exe"
      - "C:/Python314/Scripts/ninja-build"
      - "C:/Python314/Scripts/ninja.com"
      - "C:/Python314/Scripts/ninja.exe"
      - "C:/Python314/Scripts/ninja"
      - "C:/Python314/Scripts/samu.com"
      - "C:/Python314/Scripts/samu.exe"
      - "C:/Python314/Scripts/samu"
      - "C:/Python314/ninja-build.com"
      - "C:/Python314/ninja-build.exe"
      - "C:/Python314/ninja-build"
      - "C:/Python314/ninja.com"
      - "C:/Python314/ninja.exe"
      - "C:/Python314/ninja"
      - "C:/Python314/samu.com"
      - "C:/Python314/samu.exe"
      - "C:/Python314/samu"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/ninja-build.com"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/ninja-build.exe"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/ninja-build"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/ninja.com"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/ninja.exe"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/ninja"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/samu.com"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/samu.exe"
      - "C:/Program Files/Eclipse Adoptium/jdk-17.0.19.10-hotspot/bin/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/Microsoft VS Code/bin/ninja-build.com"
      - "C:/Program Files/Microsoft VS Code/bin/ninja-build.exe"
      - "C:/Program Files/Microsoft VS Code/bin/ninja-build"
      - "C:/Program Files/Microsoft VS Code/bin/ninja.com"
      - "C:/Program Files/Microsoft VS Code/bin/ninja.exe"
      - "C:/Program Files/Microsoft VS Code/bin/ninja"
      - "C:/Program Files/Microsoft VS Code/bin/samu.com"
      - "C:/Program Files/Microsoft VS Code/bin/samu.exe"
      - "C:/Program Files/Microsoft VS Code/bin/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Program Files/dotnet/ninja-build.com"
      - "C:/Program Files/dotnet/ninja-build.exe"
      - "C:/Program Files/dotnet/ninja-build"
      - "C:/Program Files/dotnet/ninja.com"
      - "C:/Program Files/dotnet/ninja.exe"
      - "C:/Program Files/dotnet/ninja"
      - "C:/Program Files/dotnet/samu.com"
      - "C:/Program Files/dotnet/samu.exe"
      - "C:/Program Files/dotnet/samu"
      - "C:/Program Files/nodejs/ninja-build.com"
      - "C:/Program Files/nodejs/ninja-build.exe"
      - "C:/Program Files/nodejs/ninja-build"
      - "C:/Program Files/nodejs/ninja.com"
      - "C:/Program Files/nodejs/ninja.exe"
      - "C:/Program Files/nodejs/ninja"
      - "C:/Program Files/nodejs/samu.com"
      - "C:/Program Files/nodejs/samu.exe"
      - "C:/Program Files/nodejs/samu"
      - "C:/ProgramData/chocolatey/bin/ninja-build.com"
      - "C:/ProgramData/chocolatey/bin/ninja-build.exe"
      - "C:/ProgramData/chocolatey/bin/ninja-build"
      - "C:/ProgramData/chocolatey/bin/ninja.com"
      - "C:/ProgramData/chocolatey/bin/ninja.exe"
      - "C:/ProgramData/chocolatey/bin/ninja"
      - "C:/ProgramData/chocolatey/bin/samu.com"
      - "C:/ProgramData/chocolatey/bin/samu.exe"
      - "C:/ProgramData/chocolatey/bin/samu"
      - "C:/Program Files/PuTTY/ninja-build.com"
      - "C:/Program Files/PuTTY/ninja-build.exe"
      - "C:/Program Files/PuTTY/ninja-build"
      - "C:/Program Files/PuTTY/ninja.com"
      - "C:/Program Files/PuTTY/ninja.exe"
      - "C:/Program Files/PuTTY/ninja"
      - "C:/Program Files/PuTTY/samu.com"
      - "C:/Program Files/PuTTY/samu.exe"
      - "C:/Program Files/PuTTY/samu"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/ninja-build.com"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/ninja-build.exe"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/ninja-build"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/ninja.com"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/ninja.exe"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/ninja"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/samu.com"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/samu.exe"
      - "C:/Users/Sameer/AppData/Local/Programs/Python/Launcher/samu"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/ninja-build.com"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/ninja-build.exe"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/ninja-build"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/ninja.com"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/ninja.exe"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/ninja"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/samu.com"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/samu.exe"
      - "C:/Program Files/JetBrains/IntelliJ IDEA 2026.1.2/bin/samu"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/ninja-build.com"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/ninja-build.exe"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/ninja-build"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/ninja.com"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/ninja.exe"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/ninja"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/samu.com"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/samu.exe"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/samu"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/ninja-build.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/ninja-build.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/ninja-build"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/ninja.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/ninja.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/ninja"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/samu.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/samu.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Links/samu"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/ninja-build.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/ninja-build.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/ninja-build"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/ninja.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/ninja.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/ninja"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/samu.com"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/samu.exe"
      - "C:/Users/Sameer/AppData/Local/Microsoft/WinGet/Packages/GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe/samu"
      - "C:/Users/Sameer/AppData/Roaming/npm/ninja-build.com"
      - "C:/Users/Sameer/AppData/Roaming/npm/ninja-build.exe"
      - "C:/Users/Sameer/AppData/Roaming/npm/ninja-build"
      - "C:/Users/Sameer/AppData/Roaming/npm/ninja.com"
      - "C:/Users/Sameer/AppData/Roaming/npm/ninja.exe"
      - "C:/Users/Sameer/AppData/Roaming/npm/ninja"
      - "C:/Users/Sameer/AppData/Roaming/npm/samu.com"
      - "C:/Users/Sameer/AppData/Roaming/npm/samu.exe"
      - "C:/Users/Sameer/AppData/Roaming/npm/samu"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/ninja-build.com"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/ninja-build.exe"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/ninja-build"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/ninja.com"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/ninja.exe"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/ninja"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/samu.com"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/samu.exe"
      - "C:/Users/Sameer/AppData/Local/PowerToys/DSCModules/samu"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/ninja-build.com"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/ninja-build.exe"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/ninja-build"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/ninja.com"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/ninja.exe"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/ninja"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/samu.com"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/samu.exe"
      - "C:/Program Files/JetBrains/CLion 2026.1.2/bin/cmake/win/x64/bin/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "C:/Users/Sameer/.gemini/antigravity/bin"
        - "C:\\Users\\Sameer\\AppData\\Roaming\\Antigravity\\bin"
        - "C:\\Program Files\\AdoptOpenJDK\\jre-11.0.8.10-hotspot\\bin"
        - "C:\\Python314\\Scripts\\"
        - "C:\\Python314\\"
        - "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.19.10-hotspot\\bin"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files\\Microsoft VS Code\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\PuTTY\\"
        - "C:\\Users\\Sameer\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\Sameer\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Program Files\\JetBrains\\IntelliJ IDEA 2026.1.2\\bin"
        - "C:\\Program Files\\JetBrains\\CLion 2026.1.2\\bin"
        - "C:\\Users\\Sameer\\AppData\\Local\\Microsoft\\WinGet\\Links"
        - "C:\\Users\\Sameer\\AppData\\Local\\Microsoft\\WinGet\\Packages\\GeodeSDK.GeodeCLI_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "C:\\Users\\Sameer\\AppData\\Roaming\\npm"
        - "C:\\Users\\Sameer\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "C:\\Program Files\\JetBrains\\CLion 2026.1.2\\bin\\cmake\\win\\x64\\bin"
...
