name: Build

on:
  push:
    branches:
      - "develop"
      - "release-*"
    paths:
      # File types
      - "**.cpp"
      - "**.h"
      - "**.java"
      - "**.ui"

      # Directories
      - "buildconfig/**"
      - "cmake/**"
      - "launcher/**"
      - "libraries/**"
      - "program_info/**"
      - "tests/**"

      # Files
      - "CMakeLists.txt"
      - "COPYING.md"

      # Workflows
      - ".github/workflows/build.yml"
      - ".github/actions/package/**"
      - ".github/actions/setup-dependencies/**"
  pull_request:
    paths:
      # File types
      - "**.cpp"
      - "**.h"
      - "**.java"
      - "**.ui"

      # Directories
      - "buildconfig/**"
      - "cmake/**"
      - "launcher/**"
      - "libraries/**"
      - "program_info/**"
      - "tests/**"

      # Files
      - "CMakeLists.txt"
      - "COPYING.md"

      # Workflows
      - ".github/workflows/build.yml"
      - ".github/actions/package/**"
      - ".github/actions/setup-dependencies/**"
  workflow_call:
    inputs:
      build-type:
        description: Type of build (Debug or Release)
        type: string
        default: Debug
  workflow_dispatch:
    inputs:
      build-type:
        description: Type of build (Debug or Release)
        type: string
        default: Debug

jobs:
  build:
    name: Build (${{ matrix.artifact-name }})

    permissions:
      # Required for vcpkg binary cache
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            artifact-name: Linux
            base-cmake-preset: linux

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    env: {}

    steps:
      ##
      # SETUP
      ##

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup dependencies
        id: setup-dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          build-type: ${{ inputs.build-type || 'Debug' }}
          artifact-name: ${{ matrix.artifact-name }}

      ##
      # BUILD
      ##

      - name: Get CMake preset
        id: cmake-preset
        env:
          BASE_CMAKE_PRESET: ${{ matrix.base-cmake-preset }}
          PRESET_TYPE: ${{ (inputs.build-type || 'Debug') == 'Debug' && 'debug' || 'ci' }}
        run: |
          echo preset="$BASE_CMAKE_PRESET"_"$PRESET_TYPE" >> "$GITHUB_OUTPUT"

      - name: Run CMake workflow
        env:
          CMAKE_PRESET: ${{ steps.cmake-preset.outputs.preset }}

          ARTIFACT_NAME: ${{ matrix.artifact-name }}-Qt6
          BUILD_PLATFORM: official
        run: |
          cmake --workflow --preset "$CMAKE_PRESET"

      ##
      # PACKAGE
      ##

      - name: Get short version
        id: short-version
        shell: bash
        run: |
          echo "version=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Package (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: ./.github/actions/package/linux
        with:
          version: ${{ steps.short-version.outputs.version }}
          build-type: ${{ steps.setup-dependencies.outputs.build-type }}
          artifact-name: ${{ matrix.artifact-name }}
          cmake-preset: ${{ steps.cmake-preset.outputs.preset }}
          qt-version: ${{ steps.setup-dependencies.outputs.qt-version }}

          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-private-key-id: ${{ secrets.GPG_PRIVATE_KEY_ID }}
