name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

  workflow_dispatch:
    inputs:
      build-type:
        description: Build type
        required: true
        default: Release
        type: choice
        options:
          - Debug
          - Release

permissions: {}

jobs:
  build:
    name: Build (${{ matrix.artifact-name }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            artifact-name: Windows-MSVC
            cmake-preset: windows_msvc
            vcvars-arch: amd64
            qt-version: 6.10.2

          - os: macos-13
            artifact-name: macOS
            cmake-preset: macos
            qt-version: 6.10.2

    defaults:
      run:
        shell: bash

    env:
      ARTIFACT_NAME: ${{ matrix.artifact-name }}-Qt6
      BUILD_PLATFORM: official
      BUILD_TYPE: ${{ inputs.build-type || 'Release' }}
      CMAKE_PRESET: ${{ matrix.cmake-preset }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup dependencies (Windows)
        if: runner.os == 'Windows'
        uses: ./.github/actions/setup-dependencies
        with:
          build-type: ${{ env.BUILD_TYPE }}
          artifact-name: ${{ matrix.artifact-name }}
          vcvars-arch: ${{ matrix.vcvars-arch }}
          qt-version: ${{ matrix.qt-version }}

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install qt cmake ninja

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            vcpkg
            build/vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}

      - name: Configure project
        run: |
          cmake --preset "$CMAKE_PRESET"

      - name: Run build
        run: |
          cmake --build --preset "$CMAKE_PRESET" --config "$BUILD_TYPE"

      - name: Get short version
        id: short-version
        run: |
          echo "version=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Package (Windows)
        if: runner.os == 'Windows'
        uses: ./.github/actions/package/windows
        with:
          version: ${{ steps.short-version.outputs.version }}
          artifact-name: ${{ matrix.artifact-name }}

      - name: Package (macOS)
        if: runner.os == 'macOS'
        uses: ./.github/actions/package/macos
        with:
          version: ${{ steps.short-version.outputs.version }}
          artifact-name: ${{ matrix.artifact-name }}