name: Development Container

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  merge_group:
    types: [checks_requested]
  pull_request:
  workflow_dispatch:

permissions: {}

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build (${{ matrix.arch }})

    permissions:
      contents: read
      packages: write

    outputs:
      image-name: ${{ steps.image-name.outputs.image-name }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            os: ubuntu-24.04-arm
          - arch: amd64
            os: ubuntu-24.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set image name
        id: image-name
        run: |
          echo "image-name=${REGISTRY}/${GITHUB_REPOSITORY_OWNER,,}/devcontainer" >> "$GITHUB_OUTPUT"

      - name: Install Podman
        uses: redhat-actions/podman-install@aea6ff44f2a4a82da13d22061ce73443a125925d # commit-aea6ff4
        # TODO(@getchoo): Always use this when the action properly supports ARM
        if: ${{ runner.arch == 'X64' || runner.arch == 'X86' }}
        with:
          github-token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Determine metadata for image
        id: image-metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ${{ steps.image-name.outputs.image-name }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.event.merge_group.base_ref == 'refs/heads/develop' }}

            type=sha
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          containerfiles: |
            ./Containerfile
          tags: ${{ steps.image-metadata.outputs.tags }}
          labels: ${{ steps.image-metadata.outputs.labels }}

      - name: Push image
        id: push-image
        if: ${{ github.event_name != 'pull_request' }}
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          tls-verify: true

      - name: Export image digest
        if: ${{ github.event_name != 'pull_request' }}
        env:
          DIGEST: ${{ steps.push-image.outputs.digest }}
        run: |
          mkdir -p "$RUNNER_TEMP"/digests
          touch "$RUNNER_TEMP"/digests/"${DIGEST#sha256:}"

      - name: Upload digest artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: digests-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  manifest:
    name: Create manifest

    needs: [ build ]
    if: ${{ github.event_name != 'pull_request' }}

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-24.04

    steps:
      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Install Podman
        # TODO(@getchoo): Always use this when the action properly supports ARM
        if: ${{ runner.arch == 'X64' || runner.arch == 'X86' }}
        uses: redhat-actions/podman-install@aea6ff44f2a4a82da13d22061ce73443a125925d # commit-aea6ff4
        with:
          github-token: ${{ github.token }}

      - name: Login to registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Determine metadata for manifest
        id: manifest-metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ${{ needs.build.outputs.image-name }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest,enable=${{ github.event.merge_group.base_ref == 'refs/heads/develop' }}

            type=sha
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag

      - name: Create manifest list
        working-directory: ${{ runner.temp }}/digests
        env:
          IMAGE_NAME: ${{ needs.build.outputs.image-name }}
        run: |
          while read -r tag; do
            podman manifest create "$tag" \
              $(printf "$IMAGE_NAME@sha256:%s " *)
          done <<< "$DOCKER_METADATA_OUTPUT_TAGS"

      - name: Push manifest
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          tags: ${{ steps.manifest-metadata.outputs.tags }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          tls-verify: true
